pastel-api:
  hostname: "127.0.0.1"
  port: 29932
  username: "4444"
  password: ""

node:
  pastel_id: jXa5335zYgxydGXsN6MA8r7BLbYzMTnKoV63sWBVmTrmhPgPutxa534KuvxB24fxwpH3jXr3wvHJUUzNQWGHPK
  server:
    listen_addresses: "0.0.0.0"
    port: 4444

p2p:
  listen_addresses: "0.0.0.0"
  port: 4454
  # default value is assigned automatically, by concatenated CLI parameter `--work-dir` and `p2p` as a subfolder
  data_dir: "path/to/p2p/data/dir"
  bootstrap_ip: "127.0.0.1"
  bootstrap_port: 1234
