pastel-api:
  hostname: "127.0.0.1"
  port: 29932
  username: "4447"
  password: ""

node:
  pastel_id: jXZDyPoescC4pgWMeD2qMzyPi5gaxMkkggrwGFAK2izTQgEkrjKqHSbG1HCfCFY9n3pAQ9q4VFHLrakL89bvfR
  server:
    listen_addresses: "0.0.0.0"
    port: 4447

p2p:
  listen_addresses: "0.0.0.0"
  port: 4457

metadb:
  http_address: "0.0.0.0:4007"
  raft_address: "0.0.0.0:4008"
  join_address: "0.0.0.0:4001"
  data_dir: "4007"