pastel-api:
  hostname: "127.0.0.1"
  port: 29932
  username: "4447"
  password: ""

node:
  pastel_id: jXZDyPoescC4pgWMeD2qMzyPi5gaxMkkggrwGFAK2izTQgEkrjKqHSbG1HCfCFY9n3pAQ9q4VFHLrakL89bvfR
  server:
    listen_addresses: "0.0.0.0"
    port: 4447

p2p:
  listen_addresses: "0.0.0.0"
  port: 4457
  memory_db: true

metadb:
  listen_address: "0.0.0.0"
  http_port: 4071
  raft_port: 4072
  data_dir: "metadb-4447"
