pastel-api:
  hostname: "127.0.0.1"
  port: 29932
  username: "4446"
  password: ""

node:
  pastel_id: jXa9V7SpRAvyJx53Jh3ffrEXxutuAeXUToePpzCsg8ucwB4rRf2zfuhQsdfKB8SEV4dTbE1HFGCdmWk4P9TENZ
  server:
    listen_addresses: "127.0.0.1"
    port: 4446
