pastel-api:
  hostname: "127.0.0.1"
  port: 29932
  username: "4445"
  password: ""

node:
  pastel_id: jXafgjYoFmDYaE6TP329RTdHRnansMDi64sdmKhdTPV4nHZ2rvyeacUWFHCoebbs7htqw6i77ViA5x7BmicRSB
  server:
    listen_addresses: "0.0.0.0"
    port: 4445

p2p:
  listen_addresses: "0.0.0.0"
  port: 4455

metadb:
  http_address: "0.0.0.0:4003"
  raft_address: "0.0.0.0:4004"
  join_address: "0.0.0.0:4001"
  data_dir: "4003"