pastel:
  hostname: "127.0.0.1"
  port: 29932
  username: "rt"
  password: "rt"
  ext_key: "jXafgjYoFmDYaE6TP329RTdHRnansMDi64sdmKhdTPV4nHZ2rvyeacUWFHCoebbs7htqw6i77ViA5x7BmicRSB"

server:
  listen_addresses: "127.0.0.1"
  port: 4445
