pastel-api:
  hostname: "127.0.0.1"
  port: 29932
  username: "4444"
  password: ""

node:
  pastel_id: jXa5335zYgxydGXsN6MA8r7BLbYzMTnKoV63sWBVmTrmhPgPutxa534KuvxB24fxwpH3jXr3wvHJUUzNQWGHPK
  server:
    listen_addresses: "0.0.0.0"
    port: 4444

p2p:
  listen_addresses: "0.0.0.0"
  port: 4454
  memory_db: true
  bootstrap_ip: "127.0.0.1"
  bootstrap_port: 1234

metadb:
  listen_address: "0.0.0.0"
  http_port: 4001
  raft_port: 4002
  data_dir: "4001"