pastel-api:
  hostname: "127.0.0.1"
  port: 29932
  username: "4446"
  password: ""

node:
  pastel_id: jXa9V7SpRAvyJx53Jh3ffrEXxutuAeXUToePpzCsg8ucwB4rRf2zfuhQsdfKB8SEV4dTbE1HFGCdmWk4P9TENZ
  server:
    listen_addresses: "0.0.0.0"
    port: 4446

p2p:
  listen_addresses: "0.0.0.0"
  port: 4456
  memory_db: true

metadb:
  listen_address: "0.0.0.0"
  http_port: 4061
  raft_port: 4062
  data_dir: "metadb-4446"
