node:
  # `pastel_id` must match to active `PastelID` from masternode.
  # To check it out first get the active outpoint from `masteronde status`, then filter the result of `tickets list id mine` by this outpoint.
  pastel_id: some-value
  server:
    # `listen_address` and `port` must match to `extAddress` from masternode.conf
    listen_addresses: "0.0.0.0"
    port: 4444

p2p:
  listen_address: "0.0.0.0"
  data_dir: "p2p"
  # bootstrap_ip: ""
  # bootstrap_port: ""

metadb:
  listen_address: "0.0.0.0"
  data_dir: "metadb"
