pastel-api:
  hostname: "127.0.0.1"
  port: 19932
  username: "rt"
  password: "rt"

node:
  pastel_id: jXXk5k99wK1ca5ZqC6cXSwiiUv57NNiEAApUBtQCNYPbgXDTVwo1k4vVb8J9CAMtnUC4QrNED4DhUGqKyEZCQS
  server:
    listen_addresses: "127.0.0.1"
    port: 4444
